### ISSUE TITLE
sync/media-player.js:49

### ISSUE THREAD

**Issue by BadySmith** [wetfish/sync#8]
/sync/media-player.js:49
                        throw Error(`${url} has no video or audio content`);
                        ^

Error: ./public/media/tiny-bird.webm has no video or audio content
    at playlist.forEach (/home/zeus/sync/media-player.js:49:31)
    at Array.forEach (<anonymous>)
    at MediaPlayer.getMediaTypes (/home/zeus/sync/media-player.js:32:23)
    at MediaPlayer.init (/home/zeus/sync/media-player.js:112:14)
    at Object.<anonymous> (/home/zeus/sync/server.js:42:13)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by itsrachelfish** [comment]
Hey there @BadySmith, that is a generic error message thrown when the try catch fails in the getMediaTypes function. https://github.com/wetfish/sync/blob/5e619b3d323dc8665af6e00818ba5557a1b63e55/media-player.js#L49

It's possible that you are getting this error because you don't have ffmpeg and ffprobe installed. The readme needs to be updated to include these programs as dependencies! :thinking:

**Comment by itsrachelfish** [comment]
The readme has been updated with more detailed usage instructions.
